# SUPER LEVEL PERMISSIONS
sudo: required

# INSTALL NEEDED SERVICES
services:
  - docker

# BUILD
before_install:
  - docker build -f ./item-service/Dockerfile -t diegosst/item-service .

# RUN
script:
  - docker run diegosst/item-service mvn test