version: "3"
services:
  redis-server:
    container_name: "redis-server"
    restart: "always"
    image: "redis"
  node-server:
    container_name: "node-server"
    restart: "always"
    build: .
    ports:
      - "9091:8081"
